# Part of this code was generated by ChatGPT in January 2025.

rm(list=ls())
library(ggplot2)
library(graphics)
data(cars)

################
################ KERNEL SMOOTHING
################

ksmooth_2 <- ksmooth(cars$speed, cars$dist, kernel = "normal", bandwidth = 2)
ksmooth_5 <- ksmooth(cars$speed, cars$dist, kernel = "normal", bandwidth = 5)
ksmooth_10 <- ksmooth(cars$speed, cars$dist, kernel = "normal", bandwidth = 10)

smooth_2 <- data.frame(speed = ksmooth_2$x, dist = ksmooth_2$y, Bandwidth = "2")
smooth_5 <- data.frame(speed = ksmooth_5$x, dist = ksmooth_5$y, Bandwidth = "5")
smooth_10 <- data.frame(speed = ksmooth_10$x, dist = ksmooth_10$y, Bandwidth = "10")

################
################ COMBINE DATA
################

smooth_data <- rbind(smooth_2, smooth_5, smooth_10)

################
################ PLOT
################

fig <- ggplot(data = cars, aes(x = speed, y = dist)) +
  geom_point(color = "black", size = 2) +
  geom_line(data = smooth_data, aes(x = speed, y = dist, color = Bandwidth), size = 1) +
  scale_color_manual(values = c("2" = "red", "5" = "green", "10" = "blue")) +
  labs(
    title = "Kernel Smoothing with Different Bandwidths",
    x = "Speed",
    y = "Distance",
    color = "Bandwidth"
  ) +
  theme_minimal()

print(fig)

ggsave(
  filename = "nonparametric.png",  # File name
  plot = fig,                      # The plot object
  width = 10,                             # Width in inches
  height = 6,                             # Height in inches
  dpi = 300,                               # Resolution in dots per inch
  bg = 'white'
)
